"""initial_schema

Revision ID: 7afd3510b18f
Revises: 
Create Date: 2026-01-29 23:37:11.738193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '7afd3510b18f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nav_nodes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_nav_nodes_geom', 'nav_nodes', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_nav_nodes_id'), 'nav_nodes', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('nav_edges',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_node', sa.BigInteger(), nullable=False),
    sa.Column('target_node', sa.BigInteger(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('base_cost', sa.Float(), nullable=False, comment='Base traversal cost (e.g., length/speed)'),
    sa.Column('capacity', sa.Float(), nullable=True, comment='Vehicle capacity per hour'),
    sa.Column('surface_type', sa.String(), nullable=True, comment='e.g., asphalt, dirt, gravel'),
    sa.ForeignKeyConstraint(['source_node'], ['nav_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_node'], ['nav_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_nav_edges_geom', 'nav_edges', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_nav_edges_id'), 'nav_edges', ['id'], unique=False)
    op.create_index(op.f('ix_nav_edges_source_node'), 'nav_edges', ['source_node'], unique=False)
    op.create_index(op.f('ix_nav_edges_target_node'), 'nav_edges', ['target_node'], unique=False)
    op.create_table('edge_dynamic_weights',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('edge_id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp_window', postgresql.TSTZRANGE(), nullable=False),
    sa.Column('weather_penalty_factor', sa.Float(), nullable=False),
    sa.Column('traffic_speed', sa.Float(), nullable=True, comment='Observed speed in km/h'),
    sa.ForeignKeyConstraint(['edge_id'], ['nav_edges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_dynamic_weights_edge_id'), 'edge_dynamic_weights', ['edge_id'], unique=False)
    op.create_index(op.f('ix_edge_dynamic_weights_id'), 'edge_dynamic_weights', ['id'], unique=False)
    op.create_index(op.f('ix_edge_dynamic_weights_timestamp_window'), 'edge_dynamic_weights', ['timestamp_window'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edge_dynamic_weights_timestamp_window'), table_name='edge_dynamic_weights')
    op.drop_index(op.f('ix_edge_dynamic_weights_id'), table_name='edge_dynamic_weights')
    op.drop_index(op.f('ix_edge_dynamic_weights_edge_id'), table_name='edge_dynamic_weights')
    op.drop_table('edge_dynamic_weights')
    op.drop_index(op.f('ix_nav_edges_target_node'), table_name='nav_edges')
    op.drop_index(op.f('ix_nav_edges_source_node'), table_name='nav_edges')
    op.drop_index(op.f('ix_nav_edges_id'), table_name='nav_edges')
    op.drop_index('idx_nav_edges_geom', table_name='nav_edges', postgresql_using='gist')
    op.drop_table('nav_edges')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_nav_nodes_id'), table_name='nav_nodes')
    op.drop_index('idx_nav_nodes_geom', table_name='nav_nodes', postgresql_using='gist')
    op.drop_table('nav_nodes')
    # ### end Alembic commands ###
